version: "3"

services:
  postgres:
    container_name: portfolio-pg
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./../../postgres_data:/var/lib/postgresql/data
